stages:
  - lint
  - release

linter:
  stage: lint
  image: python:3-slim-buster
  tags:
    - docker-build
  script:
    - pip install -U pylint flake8 tmdbv3api
    - pylint --version && pylint -E src/*.py
    - flake8 --version && flake8 src/*.py --ignore=E501 --statistics --count

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  tags:
    - docker-deploy
  needs:
    - job: linter
  rules:
    - if: $CI_COMMIT_TAG =~ /^([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9a-zA-Z.-]+))?$/
  variables:
    GIT_STRATEGY: none
  script:
    - echo "running release_job"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
