stages:
  - lint
  - build
  - test
  - upload
  - release

# --- LINT -----------------------------------------------------------------------------------

linter:
  stage: lint
  image: python:3-slim-buster
  tags:
    - docker-build
  script:
    - pip install --upgrade pip
    - python --version && pip --version
    - pip install -U pylint flake8
    - pylint --version && pylint --errors-only --disable import-error tvthekidx/*.py
    - flake8 --version && flake8 tvthekidx/*.py --ignore=E501,E722 --statistics --count

# --- BUILD ----------------------------------------------------------------------------------

build-debian-buster-x64:
    stage: build
    image: python:3-slim-buster
    tags:
        - docker-build
    artifacts:
        expire_in: 1 hour
        paths:
            - dist
    before_script:
        - apt update && apt install -y binutils
    script:
        - python --version
        - sed -i 's/^#//' requirements.txt
        - cat requirements.txt
        - pip install -r requirements.txt
        - pyinstaller --clean tvthekidx.spec
        - mv dist/tvthekidx dist/tvthekidx-buster

build-win-x64:
    stage: build
    image: docker:20.10.19-dind
    tags:
        - docker-build
    services:
        - name: docker:20.10.19-dind
          alias: docker
    artifacts:
        expire_in: 1 hour
        paths:
            - dist/win64/
    script:
        - docker run --rm -v "$(pwd):/src" ghcr.io/mplx/docker-pyinstaller:master-py3-win64

# --- TEST -----------------------------------------------------------------------------------

test-debian-buster-on-buster-x64:
    stage: test
    image: debian:buster-slim
    tags:
        - docker-build
    variables:
        GIT_STRATEGY: none
    script:
        - dist/tvthekidx-buster -h
    needs:
        - job: build-debian-buster-x64
          artifacts: true


test-debian-buster-on-bullseye-x64:
    stage: test
    image: debian:bullseye-slim
    tags:
        - docker-build
    variables:
        GIT_STRATEGY: none
    script:
        - dist/tvthekidx-buster -h
    needs:
        - job: build-debian-buster-x64
          artifacts: true

test-debian-buster-on-bookworm-x64:
    stage: test
    image: debian:bookworm-slim
    tags:
        - docker-build
    variables:
        GIT_STRATEGY: none
    script:
        - dist/tvthekidx-buster -h
    needs:
        - job: build-debian-buster-x64
          artifacts: true

# --- UPLOAD --------------------------------------------------------------------------------

upload-artifacts:
    stage: upload
    image: curlimages/curl:latest
    tags:
        - docker-deploy
    needs:
        - job: build-debian-buster-x64
          artifacts: true
        - job: build-win-x64
          artifacts: true
        - job: test-debian-buster-on-buster-x64
          artifacts: false
    rules:
        - if: $CI_COMMIT_TAG =~ /^([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9a-zA-Z.-]+))?$/
    variables:
        GIT_STRATEGY: none
        LINUX_AMD64_BINARY_BUILD: "tvthekidx-buster"
        LINUX_AMD64_BINARY: "tvthekidx"
        WIN_AMD64_BINARY: "tvthekidx.exe"
        PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}"
    script:
        - |
            echo Uploading binaries...
            curl --fail --silent --show-error --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file dist/tvthekidx-buster ${PACKAGE_REGISTRY_URL}/tvthekidx-debian-amd64
            echo
            curl --fail --silent --show-error --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file dist/win64/tvthekidx.exe ${PACKAGE_REGISTRY_URL}/tvthekidx-windows-amd64.exe
            echo

# --- RELEASE --------------------------------------------------------------------------------

release:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    tags:
        - docker-deploy
    needs:
        - job: upload-artifacts
    rules:
        - if: $CI_COMMIT_TAG =~ /^([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9a-zA-Z.-]+))?$/
    variables:
        GIT_STRATEGY: none
        LINUX_AMD64_BINARY: "tvthekidx-debian-amd64"
        WIN_AMD64_BINARY: "tvthekidx-windows-amd64.exe"
        PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}"
#    release:
#        name: 'Release $CI_COMMIT_TAG'
#        description: 'Release $CI_COMMIT_TAG'
#        tag_name: '$CI_COMMIT_TAG'
#        ref: '$CI_COMMIT_TAG'
    script:
      - |
        release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
          --assets-link "{\"name\":\"${LINUX_AMD64_BINARY}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${LINUX_AMD64_BINARY}\"}" \
          --assets-link "{\"name\":\"${WIN_AMD64_BINARY}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${WIN_AMD64_BINARY}\"}"
