[project]
name = "tvthekidx"
description = "maintain an index of downloaded tvthek content"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["tvthek", "movies"]
authors = [
  {name = "mplx", email = "developer@mplx.eu" }
]

requires-python = ">=3.9"

dynamic = [
  "version",
  "dependencies",
  "optional-dependencies"
]

# https://pypi.org/classifiers/
classifiers = [
  #   4 - Beta
  #   5 - Production/Stable
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3 :: Only",
  "Intended Audience :: Developers",
  "Intended Audience :: End Users/Desktop",
  "Topic :: Multimedia :: Video",
  "Topic :: Utilities"
]

# https://packaging.python.org/specifications/core-metadata/#project-url-multiple-use
# https://packaging.python.org/specifications/core-metadata/#home-page-optional
[project.urls]
"Homepage" = "https://gitlab.mplx.eu/scripts/tvthekidx"
"Source" = "https://gitlab.mplx.eu/scripts/tvthekidx"

[project.scripts]
tvthekidx = "tvthekidx.cli:main"

[build-system]
requires = [
  "setuptools>=64",
  "setuptools-scm>=8.0",
  "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
optional-dependencies = {dev = { file = ["requirements-dev.txt"] }}

[tool.setuptools_scm]
version_file = "./src/tvthekidx/_version.py"

